spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foody?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_PW}
            scope:
              - email
              - profile
  cache:
    type: redis
    redis:
      time-to-live: 3600 # 데이터 유지 시간
      cache-null-values: false # NUll 캐싱 여부
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

jwt:
  token:
    secret: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.security: debug
    org.springframework.web: debug
server:
  port: 8082
  tomcat:
    default-locale: ko_KR

recommend:
  server:
    url: ${DATA_URL}
